from typing import Protocol

from src.materials.domain.entities import Application, Material, PropertyDefinition


class MaterialCatalogRepository(Protocol):
    def list_all(self) -> list[Material]: ...

    def get_by_slug(self, slug: str) -> Material | None: ...

    def list_by_slugs(self, slugs: list[str]) -> list[Material]: ...

    def list_applications(self) -> list[Application]: ...

    def list_property_definitions(self) -> list[PropertyDefinition]: ...
